name: Download Lokalise translations

on:
  schedule:
    - cron: "0 2 * * 2"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Lokalise CLI
        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/v3.1.4/install.sh | sh -s -- -b ./bin v3.1.4

      - name: Pull
        env:
          VAR_LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_RO_API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_DESKTOP_PROJECT_ID }}
        run: |
          ./bin/lokalise2 \
            --token "${VAR_LOKALISE_API_TOKEN}" \
            --project-id "${VAR_LOKALISE_PROJECT_ID}" \
            file download \
            --format json \
            --export-empty-as skip \
            --export-sort first_added \
            --placeholder-format printf \
            --plural-format array \
            --indentation 2sp \
            --add-newline-eof \
            --directory-prefix src-tauri/resources/translations \
            --replace-breaks=false \
            --async

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_NEW_BRANCH_NAME: Lokalise-${{ github.run_id }}${{ github.run_attempt }}
        run: |
          git checkout -b "${GITHUB_NEW_BRANCH_NAME}"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git restore -- src-tauri/resources/translations/en.json
          git add src-tauri/resources/translations/\*.json
          if git diff --cached --quiet; then
            echo "No translation changes"
          else
            git commit -m 'Translations update'
            git push --set-upstream origin "${GITHUB_NEW_BRANCH_NAME}"
            gh pr create --base main --head "${GITHUB_NEW_BRANCH_NAME}" --title "Lokalise translations update" --body ""
          fi
